### PR TITLE
feat: allow --publish

### LINKED ISSUE #144: support -p to allow exposing ports
I tried using the `shell` option , but unfortunately the constructed command is still invalid:

```
[...] --label com.buildkite.job-id=c691aa38-56e7-4abb-8acc-8546b863420d my/image0 -p 80:8080 /bin/sh -e -c my/script.sh
```

it needs to be:

```
[...] --label com.buildkite.job-id=c691aa38-56e7-4abb-8acc-8546b863420d -p 80:8080 my/image0 /bin/sh -e -c my/script.sh
```

### PR DESCRIPTION
**Pull request by joscha**
closes #144

### CODE REVIEW

**Comment by lox** [comment]
Looks legit! Mind adding `publish` to the schema at https://github.com/buildkite-plugins/docker-buildkite-plugin/blob/master/plugin.yml?

**Comment by joscha** [comment]
> Looks legit! Mind adding `publish` to the schema at [/plugin.yml@`master`](https://github.com/buildkite-plugins/docker-buildkite-plugin/blob/master/plugin.yml) [](/buildkite-plugins/docker-buildkite-plugin/blob/HEAD@{2019-11-06T05:30:04Z}/plugin.yml)?

👍 c289efaa0eaab035b740457154308a936ac90f4f

**Comment by lox** [comment]
Many thanks!

**Comment by joscha** [comment]
Thank you!

**Comment by joscha** [comment]
any chance we can make this a `3.4.0`?

**Comment by lox** [comment]
Done! https://github.com/buildkite-plugins/docker-buildkite-plugin/releases/tag/v3.4.0

**Pull request merged**
