### PR TITLE
Add support for IPC options on docker run

### PR DESCRIPTION
**Pull request by underscorebrody**

### CODE REVIEW

**Comment by fforres** [comment]
Do you folks have any plans on merging this? 
We where looking at the cypress docs mentioning this being a source of flakiness.
https://docs.cypress.io/guides/references/error-messages.html#The-Chromium-Renderer-process-just-crashed

Anyhting we can do to help test this?

ping @lox ? :D

**Comment by jlison** [comment]
I agree with fforres. It will be great if we could get this merged as soon as possible.

**Comment by thomaspicquet** [comment]
This is a great PR, super useful in our situation, can this be merged?

**Comment by fforres** [comment]
CC @lox || @toolmantim 😄

**Comment by jlison** [comment]
Bump! 😅

**Comment by toolmantim** [comment]
Thanks @underscorebrody for the contribution, and sorry for the delay! Your changes look great… thanks for updating the readme and tests too ❤️

**Pull request merged**
