### PR TITLE
Allow `entrypoint:` to reset default entrypoint

### LINKED ISSUE #59: entrypoint should allow ""
https://github.com/buildkite-plugins/docker-buildkite-plugin/blob/master/hooks/command#L82 checks for a non-empty string in `entrypoint`, but it should allow `""` so you can reset the entrypoint without having to do weird things like `entrypoint: "/bin/sh"; shell: "-ec"`

### PR DESCRIPTION
**Pull request by lox**
Adds the ability to disable the Docker image’s entrypoint by setting `entry point: false`. This is equivalent to running `docker run --entrypoint ''`.

Closes #59.

### CODE REVIEW

**Comment by lox** [comment]
I can't figure out a good way to workaround the parsing in the bats mock library to make this change work.

**Comment by toolmantim** [comment]
Maybe we just have to comment/skip the test for this for now?

**Comment by dgarbus** [comment]
Any update on this? We're running into a case where being able to set the entrypoint to nil would be helpful.

**Comment by toolmantim** [comment]
I took a stab at this a few days ago, updated it to master, and had the same problem with `bats` and environment variables not passing through correctly, so I couldn't get the tests to work.

Though my version also supported `false` and `''` as valid values for disabling the entrypoint (by using `BUILDKITE_PLUGIN_DOCKER_PLUGIN_ENTRYPOINT:-undefined` as the default if check, instead of `false`).

Perhaps we just comment out the test, or find another way to test it?

**Comment by lox** [comment]
I merged the updated plugin tester, lemme see if I can get those tests passing now.

**Comment by pecigonzalo** [comment]
I was testing this PR and I believe its not working, I have tried setting `false` and `""` and it never sets `--entrypoint=""` which should do `--entrypoint ''`.
Could you show an example?

**Comment by toolmantim** [comment]
It's possibly a bug @pecigonzalo.

**Pull request merged**
