### PR TITLE
Handle entrypoint for set and unset variables

### PR DESCRIPTION
**Pull request by pecigonzalo**
Fixes: #73

### CODE REVIEW

**Comment by toolmantim** [comment]
Thanks for the fix @pecigonzalo!

**Comment by lox** [comment]
This broke the tests and appears to set `--entrypoint` on every invocation 🤔

**Comment by toolmantim** [comment]
😓

**Comment by pecigonzalo** [comment]
I dont see that on the test:
```
[1G   Run with BUILDKITE_COMMAND[K[75G 1/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --env BUILDKITE_JOB_ID --env BUILDKITE_BUILD_ID --env BUILDKITE_AGENT_ACCESS_TOKEN --volume /buildkite-agent:/usr/bin/buildkite-agent image:tag /bin/sh -e -c command1 "a string"
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Run with BUILDKITE_COMMAND[K
[0m[1G   Pull image first before running BUILDKITE_COMMAND with mount-build...[K[75G 2/29[2Gbats-mock(docker): got docker pull image:tag
bats-mock(docker): running echo pulled latest image
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir image:tag /bin/sh -e -c pwd
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Pull image first before running BUILDKITE_COMMAND with mount-buildkite-agent disabled[K
[0m[1G   Runs BUILDKITE_COMMAND with mount-buildkite-agent disabled[K[75G 3/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir image:tag /bin/sh -e -c pwd
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with mount-buildkite-agent disabled[K
[0m[1G   Runs BUILDKITE_COMMAND with volumes[K[75G 4/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/app --volume /var/run/docker.sock:/var/run/docker.sock --workdir /app image:tag /bin/sh -e -c echo hello world; pwd
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with volumes[K
[0m[1G   Runs BUILDKITE_COMMAND with sysctls[K[75G 5/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/app --sysctl net.ipv4.ip_forward=1 --sysctl net.unix.max_dgram_qlen=200 --workdir /app image:tag /bin/sh -e -c echo hello world; pwd
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with sysctls[K
[0m[1G   Runs BUILDKITE_COMMAND with mount-checkout=false[K[75G 6/29[2Gbats-mock(docker): got docker run -it --rm --init image:tag /bin/sh -e -c echo hello world; pwd
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with mount-checkout=false[K
[0m[1G   Runs BUILDKITE_COMMAND with mount-checkout=true[K[75G 7/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/app --workdir /app image:tag /bin/sh -e -c echo hello world; pwd
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with mount-checkout=true[K
[0m[1G   Runs BUILDKITE_COMMAND with deprecated mounts[K[75G 8/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/app --volume /var/run/docker.sock:/var/run/docker.sock --workdir /app image:tag /bin/sh -e -c echo hello world; pwd
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with deprecated mounts[K
[0m[1G   Runs BUILDKITE_COMMAND with environment[K[75G 9/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --env MY_TAG=value --env ANOTHER_TAG=llamas image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with environment[K
[0m[1G   Runs BUILDKITE_COMMAND with shm size[K[75G10/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --shm-size 100mb image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with shm size[K
[0m[1G   Runs BUILDKITE_COMMAND with propagate environment[K[75G11/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --env MY_TAG=value --env FOO --env A_VARIABLE image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with propagate environment[K
[0m[1G   Runs BUILDKITE_COMMAND with user[K[75G12/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir -u foo image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with user[K
[0m[1G   Runs BUILDKITE_COMMAND with additional groups[K[75G13/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --group-add foo --group-add bar image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with additional groups[K
[0m[1G   Runs BUILDKITE_COMMAND with propagated uid and guid[K[75G14/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir -u 123:456 image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with propagated uid and guid[K
[0m[1G   Runs BUILDKITE_COMMAND with network that doesn't exist[K[75G15/29[2Gbats-mock(docker): got docker network ls --quiet --filter name=foo
bats-mock(docker): running echo 
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): got docker network create foo
bats-mock(docker): running echo creating network foo
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --network foo image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with network that doesn't exist[K
[0m[1G   Runs BUILDKITE_COMMAND with debug mode[K[75G16/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with debug mode[K
[0m[1G   Runs BUILDKITE_COMMAND with custom runtime[K[75G17/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --runtime custom_runtime image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with custom runtime[K
[0m[1G   Runs BUILDKITE_COMMAND with entrypoint without explicit shell[K[75G18/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --entrypoint /some/custom/entry/point image:tag echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with entrypoint without explicit shell[K
[0m[1G   Runs BUILDKITE_COMMAND with entrypoint with explicit shell[K[75G19/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --entrypoint /some/custom/entry/point image:tag custom-bash -a -b echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with entrypoint with explicit shell[K
[0m[1G   Runs BUILDKITE_COMMAND with entrypoint disabled by null[K[75G20/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with entrypoint disabled by null[K
[0m[1G   Runs BUILDKITE_COMMAND with entrypoint disabled by false[K[75G21/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --entrypoint '' image:tag echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with entrypoint disabled by false[K
[0m[1G   Runs BUILDKITE_COMMAND with shell[K[75G22/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir image:tag custom-bash -a -b echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with shell[K
[0m[1G   Runs BUILDKITE_COMMAND with shell option as string[K[75G23/29[2G[1G ✓ Runs BUILDKITE_COMMAND with shell option as string[K
[0m[1G   Runs BUILDKITE_COMMAND with shell disabled[K[75G24/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir image:tag echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with shell disabled[K
[0m[1G   Runs with a command as a string[K[75G25/29[2G[1G ✓ Runs with a command as a string[K
[0m[1G   Runs with a command as an array[K[75G26/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir image:tag echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs with a command as an array[K
[0m[1G   Runs with a command as an array with a shell[K[75G27/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir image:tag custom-bash -a -b echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs with a command as an array with a shell[K
[0m[1G   Runs with a command as an array with a shell and an entrypoint[K[75G28/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --entrypoint llamas.sh image:tag custom-bash -a -b echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs with a command as an array with a shell and an entrypoint[K
[0m[1G   Doesn't disclose environment[K[75G29/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Doesn't disclose environment[K
[0m
29 tests, 0 failures
```

**Comment by lox** [comment]
Might have been in the merge to master:

https://github.com/buildkite-plugins/docker-buildkite-plugin/commit/ab66481e5ed3d2b6272255dcbcd45ab154894f40

**Comment by lox** [comment]
Nah, it's failing in 4c52eebb93e2f646aa39743a97ab726eb91a2398 too (your commit).

```
 ✗ Run with BUILDKITE_COMMAND
   (from function `assert_success' in file /usr/local/lib/bats-assert/src/assert.bash, line 114,
    in test file tests/command.bats, line 18)
     `assert_success' failed

   -- command failed --
   status : 1
   output : /Users/lachlan/Projects/buildkite/docker-buildkite-plugin/hooks/command: line 282: BUILDKITE_PLUGIN_DOCKER_ENTRYPOINT: unbound variable
   --
```

**Comment by pecigonzalo** [comment]
I cant replicate: 
```
❯ docker-compose run --rm tests
[1G   Run with BUILDKITE_COMMAND[K[75G 1/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --env BUILDKITE_JOB_ID --env BUILDKITE_BUILD_ID --env BUILDKITE_AGENT_ACCESS_TOKEN --volume /buildkite-agent:/usr/bin/buildkite-agent image:tag /bin/sh -e -c command1 "a string"
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Run with BUILDKITE_COMMAND[K
[0m[1G   Pull image first before running BUILDKITE_COMMAND with mount-build...[K[75G 2/29[2Gbats-mock(docker): got docker pull image:tag
bats-mock(docker): running echo pulled latest image
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir image:tag /bin/sh -e -c pwd
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Pull image first before running BUILDKITE_COMMAND with mount-buildkite-agent disabled[K
[0m[1G   Runs BUILDKITE_COMMAND with mount-buildkite-agent disabled[K[75G 3/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir image:tag /bin/sh -e -c pwd
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with mount-buildkite-agent disabled[K
[0m[1G   Runs BUILDKITE_COMMAND with volumes[K[75G 4/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/app --volume /var/run/docker.sock:/var/run/docker.sock --workdir /app image:tag /bin/sh -e -c echo hello world; pwd
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with volumes[K
[0m[1G   Runs BUILDKITE_COMMAND with sysctls[K[75G 5/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/app --sysctl net.ipv4.ip_forward=1 --sysctl net.unix.max_dgram_qlen=200 --workdir /app image:tag /bin/sh -e -c echo hello world; pwd
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with sysctls[K
[0m[1G   Runs BUILDKITE_COMMAND with mount-checkout=false[K[75G 6/29[2Gbats-mock(docker): got docker run -it --rm --init image:tag /bin/sh -e -c echo hello world; pwd
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with mount-checkout=false[K
[0m[1G   Runs BUILDKITE_COMMAND with mount-checkout=true[K[75G 7/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/app --workdir /app image:tag /bin/sh -e -c echo hello world; pwd
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with mount-checkout=true[K
[0m[1G   Runs BUILDKITE_COMMAND with deprecated mounts[K[75G 8/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/app --volume /var/run/docker.sock:/var/run/docker.sock --workdir /app image:tag /bin/sh -e -c echo hello world; pwd
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with deprecated mounts[K
[0m[1G   Runs BUILDKITE_COMMAND with environment[K[75G 9/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --env MY_TAG=value --env ANOTHER_TAG=llamas image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with environment[K
[0m[1G   Runs BUILDKITE_COMMAND with shm size[K[75G10/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --shm-size 100mb image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with shm size[K
[0m[1G   Runs BUILDKITE_COMMAND with propagate environment[K[75G11/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --env MY_TAG=value --env FOO --env A_VARIABLE image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with propagate environment[K
[0m[1G   Runs BUILDKITE_COMMAND with user[K[75G12/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir -u foo image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with user[K
[0m[1G   Runs BUILDKITE_COMMAND with additional groups[K[75G13/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --group-add foo --group-add bar image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with additional groups[K
[0m[1G   Runs BUILDKITE_COMMAND with propagated uid and guid[K[75G14/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir -u 123:456 image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with propagated uid and guid[K
[0m[1G   Runs BUILDKITE_COMMAND with network that doesn't exist[K[75G15/29[2Gbats-mock(docker): got docker network ls --quiet --filter name=foo
bats-mock(docker): running echo 
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): got docker network create foo
bats-mock(docker): running echo creating network foo
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --network foo image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with network that doesn't exist[K
[0m[1G   Runs BUILDKITE_COMMAND with debug mode[K[75G16/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with debug mode[K
[0m[1G   Runs BUILDKITE_COMMAND with custom runtime[K[75G17/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --runtime custom_runtime image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with custom runtime[K
[0m[1G   Runs BUILDKITE_COMMAND with entrypoint without explicit shell[K[75G18/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --entrypoint /some/custom/entry/point image:tag echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with entrypoint without explicit shell[K
[0m[1G   Runs BUILDKITE_COMMAND with entrypoint with explicit shell[K[75G19/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --entrypoint /some/custom/entry/point image:tag custom-bash -a -b echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with entrypoint with explicit shell[K
[0m[1G   Runs BUILDKITE_COMMAND with entrypoint disabled by null[K[75G20/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with entrypoint disabled by null[K
[0m[1G   Runs BUILDKITE_COMMAND with entrypoint disabled by false[K[75G21/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --entrypoint '' image:tag echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with entrypoint disabled by false[K
[0m[1G   Runs BUILDKITE_COMMAND with shell[K[75G22/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir image:tag custom-bash -a -b echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with shell[K
[0m[1G   Runs BUILDKITE_COMMAND with shell option as string[K[75G23/29[2G[1G ✓ Runs BUILDKITE_COMMAND with shell option as string[K
[0m[1G   Runs BUILDKITE_COMMAND with shell disabled[K[75G24/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir image:tag echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs BUILDKITE_COMMAND with shell disabled[K
[0m[1G   Runs with a command as a string[K[75G25/29[2G[1G ✓ Runs with a command as a string[K
[0m[1G   Runs with a command as an array[K[75G26/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir image:tag echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs with a command as an array[K
[0m[1G   Runs with a command as an array with a shell[K[75G27/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir image:tag custom-bash -a -b echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs with a command as an array with a shell[K
[0m[1G   Runs with a command as an array with a shell and an entrypoint[K[75G28/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --entrypoint llamas.sh image:tag custom-bash -a -b echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Runs with a command as an array with a shell and an entrypoint[K
[0m[1G   Doesn't disclose environment[K[75G29/29[2Gbats-mock(docker): got docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir image:tag /bin/sh -e -c echo hello world
bats-mock(docker): running echo ran command in docker
bats-mock(docker): command input is 
bats-mock(docker): command result was 0
bats-mock(docker): result 0
bats-mock(docker): unstubbing
[1G ✓ Doesn't disclose environment[K
[0m
29 tests, 0 failures

```

**Comment by lox** [comment]
I'm not actually sure what your code was meant to do here 🤔 It seems like it does the same thing as the code it was replacing! What am I missing?

**Comment by pecigonzalo** [comment]
The code its replacing was not doing that, check the last comment on: https://github.com/buildkite-plugins/docker-buildkite-plugin/pull/73 and the tests added

**Comment by pecigonzalo** [comment]
Upon further testing, `Runs BUILDKITE_COMMAND with entrypoint disabled by null` and `Runs 
BUILDKITE_COMMAND with entrypoint disabled by false` give false positives.

Small recap:
- #73 as it was, was not working as far as I could test/check (check the last comment on that PR)
- I cant see the changes here adding entrypoint everywhere nor validate your test output with `docker-compose run --rm tests` (the testing method from README.md)

**Comment by pecigonzalo** [comment]
The new code has:
```
echo "--- :docker: Running command in ${BUILDKITE_PLUGIN_DOCKER_IMAGE}"
echo -ne '\033[90m$\033[0m docker run' >&2

# Print all the arguments, with a space after, properly shell quoted
printf "%q " "${args[@]}"
echo
```

Which we now could use to validate the command better
```
@test "Runs BUILDKITE_COMMAND with entrypoint disabled by null" {
  export BUILDKITE_PLUGIN_DOCKER_IMAGE=image:tag
  export BUILDKITE_PLUGIN_DOCKER_MOUNT_BUILDKITE_AGENT=false
  export BUILDKITE_PLUGIN_DOCKER_ENTRYPOINT=''
  export BUILDKITE_COMMAND="echo hello world"

  stub docker \
    "run -it --rm --init --volume $PWD:/workdir --workdir /workdir : echo ran command in docker"

  run $PWD/hooks/command

  assert_success
  assert_output --partial "docker run -it --rm --init --volume /plugin:/workdir --workdir /workdir --entrypoint '' --label com.buildkite.job-id=1-2-3-4 image:tag echo\ hello\ world"
  assert_output --partial "ran command in docker"

  unstub docker
  unset BUILDKITE_PLUGIN_DOCKER_IMAGE
  unset BUILDKITE_PLUGIN_DOCKER_MOUNT_BUILDKITE_AGENT
  unset BUILDKITE_PLUGIN_DOCKER_ENTRYPOINT
  unset BUILDKITE_COMMAND
}```

PS: Line `echo -ne '\033[90m$\033[0m docker run' >&2` should have a space at the end to avoid making the output `run-it`:
```
docker run-it --rm
```

**Comment by lox** [comment]
I added the tests in https://github.com/buildkite-plugins/docker-buildkite-plugin/pull/131 and it's all green. 🤷🏼‍♂️

**Comment by pecigonzalo** [comment]
I sent this over Slack but I noticed a false positive in the test, check this pipeline: https://buildkite.com/coyainsurance/test/builds/9 you will see entrypoint is not disabled, as the README says, when setting it to `false` and behaves incorrectly in some other cases.
Some other cases fail because of `--init` and the issue mentioned on #120.

I did some testing of the tests, as seems like BATS is quite... tricky and I believe my test has false positives. Check my last comment here before #131

**Comment by lox** [comment]
Got it, I missed your earlier message!

**Comment by lox** [comment]
Looks like a `bats-mock` bug was resulting in a false positive, as you suggested @pecigonzalo. Fixed in https://github.com/lox/bats-mock/pull/4.

**Comment by pecigonzalo** [comment]
Awesome! Could we revisit the reversal of this PR and the test results?

**Comment by lox** [comment]
Yup!

**Pull request merged**
