### PR TITLE
Add support for `docker run --init`.

### PR DESCRIPTION
**Pull request by philwo**
This ensures that zombie processes are reaped inside the container.

### CODE REVIEW

**Comment by lox** [comment]
Seems sensible to me, I wonder if we should consider a default of `false` initially? Otherwise it's probably a breaking change for anyone currently using containers with a `tini` endpoint

**Comment by toolmantim** [comment]
If we reckon it's a new good default, we could potentially cut a new major version? May as well!

**Comment by lox** [comment]
Ok cool!

**Comment by philwo** [comment]
You're awesome. 😆 Thanks a lot for reviewing and merging!

**Pull request merged**
