### PR TITLE
Add device-level IO limit options

### PR DESCRIPTION
**Pull request by bradleyayers**
The Docker run options `--device-read-bps`, `--device-read-iops`, `--device-write-bps`, `--device-write-iops` can now be set.

### CODE REVIEW

**Review by toote — CHANGES_REQUESTED** [review]
Great implementation!

Would you mind adding tests for the options added so that we can merge it with confidence that future changes will not break it? :)

**Comment by bradleyayers** [comment]
I've pushed a new commit… I had some trouble writing tests:

- I couldn't find any instructions on how to run bats e.g. in the readme
- I installed bats and ran `bats tests/` but it failed not being able to load `load "${BATS_PLUGIN_PATH}/load.bash"`
- When I push a commit to my branch the CI doesn't run because it needs approval to start

Ideally I'd be able to test and make sure it's all good before requesting a review, so apologies for the PR churn.

**Comment by bradleyayers** [comment]
@toote ok I _think_ it might be working now

**Comment by toote** [comment]
> I've pushed a new commit… I had some trouble writing tests:
> 
> * I couldn't find any instructions on how to run bats e.g. in the readme
> * I installed bats and ran `bats tests/` but it failed not being able to load `load "${BATS_PLUGIN_PATH}/load.bash"`

The [plugin's documentation about development](https://github.com/buildkite-plugins/docker-buildkite-plugin?tab=readme-ov-file#developing) shows you how to do that either using the `bk` cli tool or the plugin tester (that runs bats)

> * When I push a commit to my branch the CI doesn't run because it needs approval to start

That is a security measure on purpose :)

> Ideally I'd be able to test and make sure it's all good before requesting a review, so apologies for the PR churn.

Any improvement is more than welcome and efforts to comply with our review is extremely appreciated :heart: In this process we all get better :)

**Review by toote — APPROVED** [review]

**Pull request merged**
