### PR TITLE
Add a shell option

### PR DESCRIPTION
**Pull request by toolmantim**
Similar to #49 this adds a `shell` option for disabling and customising the shell, and let's you run Docker commands in non-bash environments (#23).

It also disables the `shell` by default when you set an `entrypoint`, which is probably the most common need, which makes there no need for #49.

### CODE REVIEW

**Comment by toolmantim** [comment]
Also I noticed we don't have `^` and `$` on many of our option pattern checks. Any reason for that @lox?

**Comment by toolmantim** [comment]
@lox updated!

**Comment by lox** [comment]
I'd make the default `/bin/bash -e -c` to match the agent.

**Comment by toolmantim** [comment]
@lox this doesn't change the current behaviour at all though… I was thinking of doing that in a separate change. And just making it `/bin/sh -e -c`

**Comment by lox** [comment]
Yeah, fair.

**Comment by toolmantim** [comment]
This was released in [v1.3.0 (🍦 Gelato Hands)](https://github.com/buildkite-plugins/docker-buildkite-plugin/releases/tag/v1.3.0)

**Pull request merged**
